<a href="https://colab.research.google.com/github/aniilkeles/DeepLearningNotes/blob/main/RBFN/PyTorch_RBFN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Radial Basis Function Neural Network için ben iris veri seti kullanacağım.

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
iris = load_iris()

In [14]:
df = pd.DataFrame(iris.data , columns = iris.feature_names)

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [17]:
X = iris.data
y = iris.target

In [18]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [23]:
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [24]:
# train-test-split

In [25]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=15)

In [26]:
def to_tensor(data,target):
  return torch.tensor(data,dtype=torch.float32) , torch.tensor(target , dtype=torch.long)

In [27]:
X_train , y_train = to_tensor(X_train,y_train)

In [33]:
X_test , y_test = to_tensor(X_test,y_test)

In [34]:
type(X_test)

torch.Tensor

In [35]:
type(y_train)

torch.Tensor

In [36]:
type(y_test)

torch.Tensor

In [37]:
type(X_train)

torch.Tensor

In [38]:
# RBFN modeli oluşturmak ve RBFN Kernel'ın tanımlanması

In [39]:
def rbf_kernel(X,centers,beta):
  return torch.exp(-beta*torch.cdist(X,centers)**2)

In [40]:
class RBFN(nn.Module):
  def __init__(self,input_dim,num_centers,output_dim):
    super(RBFN,self).__init__() # Neural Network initiliazer çağırma işlemi
    self.centers = nn.Parameter(torch.randn(num_centers,input_dim)) # rbfn merkezlerini rastgele başlatma
    self.beta  = nn.Parameter(torch.ones(1)*2.0) # beta parametresi rbfn nin genişliğini kontrol edecek
    self.linear = nn.Linear(num_centers,output_dim) # outputu tam bağlantılı katmana yönlendir.
  def forward(self,x):
    # rbf çekirdek fonksiyonunu hesaplama
    phi = rbf_kernel(x,self.centers,self.beta)
    return self.linear(phi)

In [43]:
num_centers = 10
model = RBFN(4,10,3)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.01)

num_epochs = 100
for epoch in range(num_epochs):
  optimizer.zero_grad()
  outputs = model(X_train)
  loss = criterion(outputs,y_train)
  loss.backward()
  optimizer.step()

  if (epoch+1) % 10 == 0:
    print(f"Epoch : {epoch+1}/{num_epochs} , Loss : {loss.item():.4f}")

Epoch : 10/100 , Loss : 1.0737
Epoch : 20/100 , Loss : 1.0387
Epoch : 30/100 , Loss : 0.9823
Epoch : 40/100 , Loss : 0.9035
Epoch : 50/100 , Loss : 0.8051
Epoch : 60/100 , Loss : 0.6908
Epoch : 70/100 , Loss : 0.5764
Epoch : 80/100 , Loss : 0.4773
Epoch : 90/100 , Loss : 0.3964
Epoch : 100/100 , Loss : 0.3341


In [44]:
with torch.no_grad():
  y_pred = model(X_test) # test verisi ile tahmin
  accuracy = (torch.argmax(y_pred,axis=1)==y_test).float().mean().item()
  print(f"Accuracy : {accuracy}")

Accuracy : 0.9555555582046509
